- name: Setup Nginx and User on Slave Server
  hosts: private
  become: yes

  vars:
    package_path: /tmp/nginx-packages.tar.gz
    extract_path: /tmp/nginx-packages

  tasks:

    # -----------------------------
    # Copy nginx package
    # -----------------------------
    - name: Copy nginx package tar
      copy:
        src: files/nginx-packages.tar.gz
        dest: "{{ package_path }}"

    # -----------------------------
    # Extract package
    # -----------------------------
    - name: Extract nginx packages
      unarchive:
        src: "{{ package_path }}"
        dest: /tmp/
        remote_src: yes

    # -----------------------------
    # Install nginx offline
    # -----------------------------
    - name: Install nginx RPMs
      command: >
        dnf install {{ extract_path }}/*.rpm
        --disablerepo=*
        --allowerasing
        -y

    # -----------------------------
    # Start and enable nginx
    # -----------------------------
    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    # -----------------------------
    # Create slave-user
    # -----------------------------
    - name: Create slave-user
      user:
        name: slave-user
        shell: /bin/bash
        create_home: yes

    # -----------------------------
    # Set password for slave-user
    # -----------------------------
    - name: Set password for slave-user
      user:
        name: slave-user
        password: "{{ 'Password@123' | password_hash('sha512') }}"

    # -----------------------------
    # Enable password authentication
    # -----------------------------
    - name: Enable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'

    - name: Enable challenge response
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication yes'

    # -----------------------------
    # Restart SSH service
    # -----------------------------
    - name: Restart SSH
      service:
        name: sshd
        state: restarted

    # -----------------------------
    # Copy SSH access from ec2-user
    # -----------------------------
    - name: Copy authorized_keys
      copy:
        src: /home/ec2-user/.ssh/authorized_keys
        dest: /home/slave-user/.ssh/authorized_keys
        owner: slave-user
        group: slave-user
        mode: '0600'
        remote_src: yes

    - name: Set permissions for .ssh
      file:
        path: /home/slave-user/.ssh
        state: directory
        owner: slave-user
        group: slave-user
        mode: '0700'